### ISSUE TITLE
Figure out how to track_state_changes on entities that will be discovered

### ISSUE THREAD

**Issue by jseidl** [jseidl/ha-room#2]
While using discovery, entities might not be ready on startup. Figure out a way to either wait for them or track them whenever they become available.

Ref: https://github.com/jseidl/ha-room/issues/1

**Comment by jseidl** [comment]
One option that comes to mind would be to have a service that you could call upon devices' discovery that would reapply the `track_state_changes` or either listen for HA's startup complete signal and reapply.

**Comment by jseidl** [comment]
Tagging @syphernl on this issue so he gets updates on this.

**Comment by syphernl** [comment]
> One option that comes to mind would be to have a service that you could call upon devices' discovery that would reapply the `track_state_changes` or either listen for HA's startup complete signal and reapply.

Listening for HA startup complete would probably be the easiest (for the end-user) but there may be no guarantee that the devices are there that time. However, when I get a push message from HA that it has been restarted and open the interface immediately all Zigbee2mqtt/Zwave2mqtt devices are showing up so based on that it has a very good chance of working.

**Comment by jseidl** [comment]
@syphernl will try to get this sorted out asap. Meanwhile you can put those sensors in template binary sensors or groups then add those to the configuration. Can you test if this works?

**Comment by ThePirat91** [comment]
Hello guys, any news on this?
It would be so much appreciated....
I have a lot of errors of this type on HA upon restart and room component doesn't work at all with these entities....

`2020-02-06 09:51:03 ERROR (MainThread) [custom_components.room.binary_sensor] binary_sensor.living_room_hue_motion_sensor_occupancy entity is not found`

Thanks! :)

**Comment by jseidl** [comment]
Sorry folks, still haven't figured out how to solve this. 

So far I've thought of two workarounds:
- A template sensor that gets the value from the sensor. 
- Using a group (e.g. group.motion_living_room) and adding your motion sensors for that room in a group. 

I actually do both because I have multiple multisensors in a room. I add them to a group and I have a [Template Binary Sensor](https://www.home-assistant.io/integrations/binary_sensor.template/) that gets the value from the group (just for the sake of `device_class` actually).

Hope that helps!

**Comment by ThePirat91** [comment]
Ok, so we couldn't actually use the "motion sensors group" directly on room-component config?
Is the template mandatory for the component job?
Thanks!

**Comment by jseidl** [comment]
> Ok, so we couldn't actually use the "motion sensors group" directly on room-component config?
> Is the template mandatory for the component job?
> Thanks!

I believe you can use the `group` component directly. Shouldn't be required to have the template sensor.

**Comment by ThePirat91** [comment]
Ok, I'll try and let you know.
Thanks!

**Comment by ThePirat91** [comment]
Jdeidl could you post your template binary sensor for one of your groups?
Thanks

**Comment by jseidl** [comment]
> Jdeidl could you post your template binary sensor for one of your groups?
> Thanks

Sure, here you go:

```
group:
  motion_living_room:
    name: Motion (Living Room)
    entities:
      - binary_sensor.motion_meistersensor_living_room
      - binary_sensor.zooz_zse40_gamma_motion
      - group.motion_dining_room
      - binary_sensor.motion_blueiris_living_room
      - binary_sensor.motion_blueiris_bookshelf

binary_sensor:
  - platform: template
    sensors:
      motion_living_room:
        friendly_name: "Motion (Living Room)"
        device_class: motion
        value_template: "{{ is_state('group.motion_living_room', 'on') }}"
```

My dining room is pretty small and part of the living room so I use their motion sensor's group as part of living room's group.

**Comment by ThePirat91** [comment]
Ok, thanks mate!

**Comment by jseidl** [comment]
> Ok, thanks mate!

Most welcome! Added this info to `README.md` for future reference

**Comment by ThePirat91** [comment]
Just noted. Thanks again!

**Comment by ThePirat91** [comment]
Hello, after a while I got my head back on this project again but I'm fighting the same problems as I did.
I am not able to make the addon works as it should....
Below a room configuration of mine (all rooms have been configured with the same template)

groups.yaml
```
bathroom_motion_sensors:
  name: Bathroom Motion Sensors
  all: true
  icon: mdi:motion-sensor
  entities: 
    - binary_sensor.bathroom_mijia_motion_sensor_occupancy
    - binary_sensor.bathroom_zwave_motion_sensor_occupancy
```

rooms.yaml
```
bathroom:
  name: "Bathroom"
  presence_sensors:
    - group.bathroom_motion_sensors
  presence_hold_sensors:
    - light.bathroom
  icon: 'mdi:paper-roll-outline'
  on_states:
    - on
    - playing
    - home
  clear_timeout: 20
```
The problem is that the entities "switch.presence_hold_bathroom" and "binary_sensor.room_bathroom" never switch to 'on' or 'occupied' state.
Is there something wrong with my config?
Thanks
